// Lazy-loaded lyric lines for line-level search.
//
// The lines used to ship inside postIndex.json (and therefore inside the main
// JS bundle). They now live in /data/search-lines.json — a slug → [lines] map
// generated by scripts/generatePostIndex.js — and are fetched only when the
// user actually opens search.

let cache = null;
let pending = null;

export function linesLoaded() {
  return cache !== null;
}

export function loadSearchLines() {
  if (cache) return Promise.resolve(cache);
  if (!pending) {
    pending = fetch("/data/search-lines.json")
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error("search-lines yüklenemedi"))))
      .then((data) => {
        cache = data || {};
        return cache;
      })
      .catch(() => {
        cache = {};
        return cache;
      });
  }
  return pending;
}

export function linesFor(slug) {
  return (cache && cache[slug]) || [];
}
