// Generated by scripts/generateTranslations.js.
export const spanishTranslationPaths = [
  "/es",
  "/es/rose-bruno-mars-apt",
  "/es/huntr-x-golden",
  "/es/lady-gaga-bruno-mars-die-with-a-smile",
  "/es/billie-eilish-birds-of-a-feather",
  "/es/alex-warren-ordinary",
  "/es/billie-eilish-wildflower",
  "/es/jimin-who",
  "/es/jennie-like-jennie"
];
