import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildSpanishTranslations } from "./lib/spanishTranslations.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = process.env.ACL_CONTENT_OUTPUT ? path.resolve(process.env.ACL_CONTENT_OUTPUT) : ROOT;
const posts = JSON.parse(await readFile(path.join(ROOT, "src/data/posts.json"), "utf8"));
const text = await readFile(path.join(ROOT, "src/data/translations/es/submitted-2026-09-07.md"), "utf8");
const translations = buildSpanishTranslations(text, posts);
const directory = path.join(OUTPUT, "public/data/translations/es");
await mkdir(directory, { recursive: true });
for (const filename of await readdir(directory)) {
  if (filename.endsWith(".json") && !translations.some((item) => `${item.slug}.json` === filename)) await unlink(path.join(directory, filename));
}
for (const item of translations) await writeFile(path.join(directory, `${item.slug}.json`), JSON.stringify(item));
await mkdir(path.join(OUTPUT, "src/data"), { recursive: true });
await writeFile(path.join(OUTPUT, "src/data/translationIndex.json"), JSON.stringify(translations.map(({ sections, ...item }) => item), null, 2) + "\n");
await mkdir(path.join(OUTPUT, "server"), { recursive: true });
await writeFile(path.join(OUTPUT, "server/translationRoutes.js"), `// Generated by scripts/generateTranslations.js.\nexport const spanishTranslationPaths = ${JSON.stringify(["/es", ...translations.map((item) => item.path)], null, 2)};\n`);
console.log(`Generated ${translations.length} Spanish translations; ${translations.reduce((sum, item) => sum + item.lineCount, 0)} supplied lines preserved.`);
