import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const posts = JSON.parse(await readFile(path.join(ROOT, "src/data/posts.json"), "utf8"));
const artistsRaw = JSON.parse(await readFile(path.join(ROOT, "src/data/artists.json"), "utf8"));

// Categories present in the WordPress export but no longer attached to a post.
const legacyOnlyTerms = {
  bi: "B.I",
  "damiano-david": "Damiano David",
  hozier: "Hozier",
  "i-dle": "i-dle",
  "if-youre-looking-for-a-new-best-friend": "If You’re Looking For A New Best Friend",
  "love-yourself-her": "Love Yourself: Her",
  uncategorized: "Uncategorized",
  "we-are": "We Are",
  folklore: "Folklore",
};

function normalize(value = "") {
  return String(value).trim().toLocaleLowerCase("en-US");
}

function slugify(value = "") {
  return String(value).toLowerCase()
    .replace(/\u0131/g, "i").replace(/\u011f/g, "g").replace(/\u00fc/g, "u")
    .replace(/\u015f/g, "s").replace(/\u00f6/g, "o").replace(/\u00e7/g, "c")
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function albumNameFor(post) {
  return String(post.spotify?.album?.name || post.spotify?.albumName || post.categories?.[1] || "Tekli").trim();
}

function albumArtistFor(post) {
  return String(
    post.spotify?.albumArtist
      || post.spotify?.album?.artist
      || post.spotify?.artistName
      || post.spotify?.artist?.name
      || post.artist
      || "",
  ).trim();
}

const performerNames = new Set(
  posts.flatMap((post) => String(post.artist || "").split(/\s*,\s*/).map(normalize).filter(Boolean)),
);

const categorySlugUse = new Map();
for (const post of posts) {
  const credits = new Set(String(post.artist || "").split(/\s*,\s*/).map(normalize));
  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    const name = normalize(post.categories?.[index]);
    if (!credits.has(name)) continue;
    const key = `${name}::${post.category_slugs[index]}`;
    categorySlugUse.set(key, (categorySlugUse.get(key) || 0) + 1);
  }
}

const preferredArtistByName = new Map();
for (const artist of artistsRaw) {
  const name = normalize(artist.name);
  if (!artist.slug || !performerNames.has(name)) continue;
  const current = preferredArtistByName.get(name);
  const score = categorySlugUse.get(`${name}::${artist.slug}`) || 0;
  const currentScore = current ? categorySlugUse.get(`${name}::${current.slug}`) || 0 : -1;
  if (!current || score > currentScore) preferredArtistByName.set(name, artist);
}

const albumTargetsByCategory = new Map();
const albumTargetsByName = new Map();
const legacyAlbumRedirects = {};
function addTarget(map, key, target) {
  if (!map.has(key)) map.set(key, new Map());
  const targets = map.get(key);
  targets.set(target, (targets.get(target) || 0) + 1);
}

for (const post of posts) {
  const albumName = albumNameFor(post);
  if (!albumName || albumName === "Tekli") continue;
  const normalizedAlbumName = normalize(albumName);
  const target = `/album/${slugify(`${albumArtistFor(post)}-${albumName}`)}`;
  const legacyAlbumSlug = slugify(`${post.artist}-${albumName}`);
  const canonicalAlbumSlug = target.replace(/^\/album\//, "");
  if (legacyAlbumSlug && legacyAlbumSlug !== canonicalAlbumSlug) {
    legacyAlbumRedirects[legacyAlbumSlug] = target;
  }
  addTarget(albumTargetsByName, normalizedAlbumName, target);

  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    if (normalize(post.categories?.[index]) !== normalizedAlbumName) continue;
    addTarget(albumTargetsByCategory, post.category_slugs[index], target);
  }
}

function strongestTarget(targets) {
  return [...(targets || new Map()).entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
}

const terms = new Map(artistsRaw.filter((artist) => artist.slug).map((artist) => [artist.slug, artist.name]));
for (const post of posts) {
  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    const slug = post.category_slugs[index];
    if (!slug) continue;
    if (!terms.has(slug)) terms.set(slug, post.categories?.[index] || slug);
  }
}
for (const [slug, name] of Object.entries(legacyOnlyTerms)) terms.set(slug, name);

const redirects = {};
for (const [slug, name] of [...terms].sort(([a], [b]) => a.localeCompare(b))) {
  const artist = preferredArtistByName.get(normalize(name));
  if (artist) {
    redirects[slug] = `/artist/${artist.slug}`;
    continue;
  }

  redirects[slug] = strongestTarget(albumTargetsByCategory.get(slug))
    || strongestTarget(albumTargetsByName.get(normalize(name)))
    || "/discover";
}

const output = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
  + `export const legacyCategoryRedirects = ${JSON.stringify(redirects, null, 2)};\n`;
const outputPath = path.join(ROOT, "server/legacyCategoryRedirects.js");
await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");

const albumRedirectOutput = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
  + `export const legacyAlbumRedirects = ${JSON.stringify(legacyAlbumRedirects, null, 2)};\n`;
await writeFile(path.join(ROOT, "server/legacyAlbumRedirects.js"), albumRedirectOutput, "utf8");

const wxrPath = path.join(ROOT, "data/raw/acupoflyrics-export.xml");
const pathRedirectOutputPath = path.join(ROOT, "server/legacyCategoryPathRedirects.js");
try {
  const wxr = await readFile(wxrPath, "utf8");
  const wxrCategories = new Map();
  for (const match of wxr.matchAll(/<wp:category>([\s\S]*?)<\/wp:category>/g)) {
    const block = match[1];
    const slug = block.match(/<wp:category_nicename><!\[CDATA\[([^\]]+)\]\]><\/wp:category_nicename>/)?.[1]?.trim();
    const parent = block.match(/<wp:category_parent><!\[CDATA\[([^\]]*)\]\]><\/wp:category_parent>/)?.[1]?.trim();
    if (slug) wxrCategories.set(slug, { slug, parent });
  }

  const pathRedirects = {};
  for (const category of wxrCategories.values()) {
    if (!category.parent || !redirects[category.slug]) continue;
    const chain = [category.slug];
    const seen = new Set(chain);
    let parent = category.parent;
    while (parent && !seen.has(parent)) {
      chain.unshift(parent);
      seen.add(parent);
      parent = wxrCategories.get(parent)?.parent || "";
    }
    const childTarget = redirects[category.slug];
    const nearestArchive = childTarget === "/discover" ? redirects[category.parent] : childTarget;
    pathRedirects[`/category/${chain.join("/")}`] = nearestArchive || childTarget;
  }

  const pathOutput = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
    + `export const legacyCategoryPathRedirects = ${JSON.stringify(pathRedirects, null, 2)};\n`;
  await writeFile(pathRedirectOutputPath, pathOutput, "utf8");
  console.log(`Generated ${Object.keys(pathRedirects).length} hierarchical WordPress category redirects.`);
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
  try {
    await readFile(pathRedirectOutputPath, "utf8");
    console.log("Kept the checked-in hierarchical category redirect manifest (raw WXR not present).");
  } catch (manifestError) {
    if (manifestError?.code !== "ENOENT") throw manifestError;
    await writeFile(pathRedirectOutputPath, "// Generated fallback; refresh with data/raw/acupoflyrics-export.xml available.\nexport const legacyCategoryPathRedirects = {};\n", "utf8");
  }
}

const reservedRootSlugs = new Set([
  "admin",
  "album",
  "albumler",
  "api",
  "artist",
  "ceviri",
  "collection",
  "discover",
  "genre",
  "gizlilik",
  "hakkimizda",
  "iletisim",
  "kesfet",
  "listeler",
  "mood",
  "muzik-listeleri",
  "old-home",
  "pop-gunlugu",
  "search",
  "sanatci",
  "sanatcilar",
  "sarkilar",
  "song",
]);

const exactAliases = new Map();
const aliasUse = new Map();
function addAliasUse(alias, destination) {
  if (!alias || reservedRootSlugs.has(alias)) return;
  if (!aliasUse.has(alias)) aliasUse.set(alias, new Set());
  aliasUse.get(alias).add(destination);
}

function addExactAlias(alias, destination) {
  if (!alias || reservedRootSlugs.has(alias)) return;
  const current = exactAliases.get(alias);
  if (current && current !== destination) return;
  exactAliases.set(alias, destination);
}

for (const post of posts) {
  if (!post.slug) continue;
  const destination = `/${post.slug}/`;
  addExactAlias(String(post.slug).toLowerCase(), destination);
  addExactAlias(String(post.oldSlug || "").toLowerCase(), destination);
  addAliasUse(slugify(post.song || ""), destination);

  const primaryArtist = String(post.artist || "").split(/\s*,\s*/)[0];
  addAliasUse(slugify(`${primaryArtist} ${post.song || ""}`), destination);
}

const postRedirects = Object.fromEntries(
  [
    ...exactAliases.entries(),
    ...[...aliasUse.entries()]
      .filter(([, targets]) => targets.size === 1)
      .map(([alias, targets]) => [alias, [...targets][0]]),
  ].sort(([a], [b]) => a.localeCompare(b)),
);
const postOutput = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
  + `export const legacyPostRedirects = ${JSON.stringify(postRedirects, null, 2)};\n`;
await writeFile(path.join(ROOT, "server/legacyPostRedirects.js"), postOutput, "utf8");

console.log(`Generated ${Object.keys(redirects).length} WordPress category redirects.`);
console.log(`Generated ${Object.keys(legacyAlbumRedirects).length} legacy album redirects.`);
console.log(`Generated ${Object.keys(postRedirects).length} nested WordPress post redirects.`);
