import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const posts = JSON.parse(await readFile(path.join(ROOT, "src/data/posts.json"), "utf8"));
const artistsRaw = JSON.parse(await readFile(path.join(ROOT, "src/data/artists.json"), "utf8"));

// Categories present in the WordPress export but no longer attached to a post.
const legacyOnlyTerms = {
  bi: "B.I",
  "damiano-david": "Damiano David",
  hozier: "Hozier",
  "i-dle": "i-dle",
  "if-youre-looking-for-a-new-best-friend": "If You’re Looking For A New Best Friend",
  "love-yourself-her": "Love Yourself: Her",
  uncategorized: "Uncategorized",
  "we-are": "We Are",
  folklore: "Folklore",
};

function normalize(value = "") {
  return String(value).trim().toLocaleLowerCase("en-US");
}

function slugify(value = "") {
  return String(value).toLowerCase()
    .replace(/\u0131/g, "i").replace(/\u011f/g, "g").replace(/\u00fc/g, "u")
    .replace(/\u015f/g, "s").replace(/\u00f6/g, "o").replace(/\u00e7/g, "c")
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function albumNameFor(post) {
  return String(post.spotify?.album?.name || post.spotify?.albumName || post.categories?.[1] || "Tekli").trim();
}

const performerNames = new Set(
  posts.flatMap((post) => String(post.artist || "").split(/\s*,\s*/).map(normalize).filter(Boolean)),
);

const categorySlugUse = new Map();
for (const post of posts) {
  const credits = new Set(String(post.artist || "").split(/\s*,\s*/).map(normalize));
  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    const name = normalize(post.categories?.[index]);
    if (!credits.has(name)) continue;
    const key = `${name}::${post.category_slugs[index]}`;
    categorySlugUse.set(key, (categorySlugUse.get(key) || 0) + 1);
  }
}

const preferredArtistByName = new Map();
for (const artist of artistsRaw) {
  const name = normalize(artist.name);
  if (!performerNames.has(name)) continue;
  const current = preferredArtistByName.get(name);
  const score = categorySlugUse.get(`${name}::${artist.slug}`) || 0;
  const currentScore = current ? categorySlugUse.get(`${name}::${current.slug}`) || 0 : -1;
  if (!current || score > currentScore) preferredArtistByName.set(name, artist);
}

const albumTargetsByCategory = new Map();
const albumTargetsByName = new Map();
function addTarget(map, key, target) {
  if (!map.has(key)) map.set(key, new Map());
  const targets = map.get(key);
  targets.set(target, (targets.get(target) || 0) + 1);
}

for (const post of posts) {
  const albumName = albumNameFor(post);
  if (!albumName || albumName === "Tekli") continue;
  const normalizedAlbumName = normalize(albumName);
  const target = `/album/${slugify(`${post.artist}-${albumName}`)}`;
  addTarget(albumTargetsByName, normalizedAlbumName, target);

  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    if (normalize(post.categories?.[index]) !== normalizedAlbumName) continue;
    addTarget(albumTargetsByCategory, post.category_slugs[index], target);
  }
}

function strongestTarget(targets) {
  return [...(targets || new Map()).entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
}

const terms = new Map(artistsRaw.map((artist) => [artist.slug, artist.name]));
for (const post of posts) {
  for (let index = 0; index < (post.category_slugs || []).length; index += 1) {
    const slug = post.category_slugs[index];
    if (!terms.has(slug)) terms.set(slug, post.categories?.[index] || slug);
  }
}
for (const [slug, name] of Object.entries(legacyOnlyTerms)) terms.set(slug, name);

const redirects = {};
for (const [slug, name] of [...terms].sort(([a], [b]) => a.localeCompare(b))) {
  const artist = preferredArtistByName.get(normalize(name));
  if (artist) {
    redirects[slug] = `/artist/${artist.slug}`;
    continue;
  }

  redirects[slug] = strongestTarget(albumTargetsByCategory.get(slug))
    || strongestTarget(albumTargetsByName.get(normalize(name)))
    || "/discover";
}

const output = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
  + `export const legacyCategoryRedirects = ${JSON.stringify(redirects, null, 2)};\n`;
const outputPath = path.join(ROOT, "server/legacyCategoryRedirects.js");
await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");

const postRedirects = Object.fromEntries(
  posts
    .filter((post) => post.slug)
    .map((post) => [String(post.slug).toLowerCase(), `/${post.slug}/`])
    .sort(([a], [b]) => a.localeCompare(b)),
);
const postOutput = `// Generated by scripts/generateLegacyCategoryRedirects.js.\n`
  + `export const legacyPostRedirects = ${JSON.stringify(postRedirects, null, 2)};\n`;
await writeFile(path.join(ROOT, "server/legacyPostRedirects.js"), postOutput, "utf8");

console.log(`Generated ${Object.keys(redirects).length} WordPress category redirects.`);
console.log(`Generated ${Object.keys(postRedirects).length} nested WordPress post redirects.`);
